version: '3.0'

services:
  strapi:
    container_name: strapi
    image: vshadbolt/strapi
    restart: unless-stopped
    ports:
      - "1337:1337"
    environment:
      ADMIN_URL: tobemodified #ex. https://api.example.com/admin
      PUBLIC_URL: tobemodified #ex. https://api.example.com
      IMG_ORIGIN: "toBeModified1,toBeModified2" #ex. 'self',data:,blob:,api.example.com,market-assets.strapi.io
      CORS_ORIGIN: "toBeModified1,toBeModified2" #ex. https://mywebsite.example.com,https://api.example.com
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapiDB
      DATABASE_PORT: 5432
      DATABASE_NAME: tobemodified #ex. strapi
      DATABASE_USERNAME: tobemodified #ex. strapi
      DATABASE_PASSWORD: tobemodified #ex. strapi
      DATABASE_SSL: false
      JWT_SECRET: tobemodified #ex. JrWfVf/o9TbWQmpMgsJaYp==
      ADMIN_JWT_SECRET: tobemodified #ex. MCpf2/FMiCJthF5d6Qup6iG==
      APP_KEYS: toBeModified1,toBeModified2 #ex. w9/ZTuHUWNF2EP8gdfPcNn==,LqXKC52TsN/z/Y2rUGTa6m==,d7EKo2Tp9SiGf82ZqrmSnB==,TAu2SJx6BDc7aYUyqiwxKs==
      API_TOKEN_SALT: tobemodified #ex. j43/kBRfXULfPpJnzPCJzi==
      TRANSFER_TOKEN_SALT: tobemodified #ex. GCX3NkRSyHrDxhfgwnmCm3==
      NODE_ENV: development # or production
      BUILD: true
      UPGRADE: false
    volumes:
      - ./app:/srv/app # to use an existing project or create a new project inside the folder ./app
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tobemodified #ex. strapi
      POSTGRES_USER: tobemodified #ex. strapi
      POSTGRES_PASSWORD: tobemodified #ex. strapi
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - strapi
  
volumes:
  postgres:
    external: true
    name: postgres

networks:
  strapi:
    name: Strapi
    driver: bridge